### ISSUE TITLE
Where is this api from?

### ISSUE THREAD

**Issue by RUGMJ** [NCPlayz/classcharts.py#5]
Is there any documentation for the api itself? I'm trying to make a JavaScript wrapper so I can make a school project much easier. Where did you find the information?

**Comment by olijeffers0n** [comment]
I mean, i'm sure that you could build one from this project. As far as i could tell, there is not any documentation. I even asked their customer support to which they said that there isn't an API. 

I think that they have reversed engineered the API requests that go when you use the website, however i may be wrong 😄

**Comment by RUGMJ** [comment]
Thanks for the reply, I see this API is around the Student view I'm trying to get the timetable of a each student who signs up to my application. But I'm not aware of any student logins in our school. But there is a app for parents to view our timetables which looks like it gets it from class charts. It would be a lot easier to reverse engineer the class charts api than the schools app because the app is on mobile devices but class charts is a web page.

**Comment by olijeffers0n** [comment]
Sorry for the slow reply

Right... So lemme get this straight

You want to get a student's timetable but without their user key? This is not possible with this API. I think what you may be talking about here: _But there is a app for parents to view our timetables_ Is that they have the PARENT key for a user. If it is a custom app then idrk however ik that you get a student token and a parent token. This is just for the student token as far as i am aware. 

If you are making an application you could just ask the user for their details when they sign up...? 

Please do reply if you have any further questions, if not my discord is Ollie#0175

> Thanks for the reply, I see this API is around the Student view I'm trying to get the timetable of a each student who signs up to my application. But I'm not aware of any student logins in our school. But there is a app for parents to view our timetables which looks like it gets it from class charts. It would be a lot easier to reverse engineer the class charts api than the schools app because the app is on mobile devices but class charts is a web page.

**Comment by NCPlayz** [comment]
> I mean, i'm sure that you could build one from this project. As far as i could tell, there is not any documentation. I even asked their customer support to which they said that there isn't an API. 
> 
> 
> 
> I think that they have reversed engineered the API requests that go when you use the website, however i may be wrong 😄 

You are correct. I did reverse engineer the API myself. Seems like I didn't get notifications for this issue until today.
